### ISSUE TITLE
Can't install YouTube 

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [gnuhead-chieb/revanced-automatic-builder#15]
![Screenshot_2023-01-28-14-26-39-74_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/45184918/215269551-814e9c39-9201-4dd2-ac6f-73c972afc14e.jpg)

![Screenshot_2023-01-28-14-27-15-06_3d73e98b1ad3bd2575f7a56513d89a0c.jpg](https://user-images.githubusercontent.com/45184918/215269554-547fe2ce-774c-43d8-af18-89586aead44d.jpg)

It say that file already exists

If you update your program how can I upgrade?

How can I fix it?

**Comment by jojojojojoj5564656465465** [comment]
It find keystore

**Comment by gnuhead-chieb** [comment]
if you have keystore, rename it to youtube-patched.keystore and save it to ~/.revanced

if not, uninstall app and install again

**Comment by jojojojojoj5564656465465** [comment]
The solution was to remove all the updates from the original YouTube app.
Thank you for your app

**Comment by jojojojojoj5564656465465** [comment]
https://github.com/charmbracelet/gum

I think it would make your script better.

Could you add exit options & and color if I have installed but late in update

**Comment by gnuhead-chieb** [comment]
> https://github.com/charmbracelet/gum
> 
> I think it would make your script better.

Rejected.I don't want to add external dependencies because it makes more bloat.
Instead, I am planning to support simple GUI for termux by using [termux-dialog](https://wiki.termux.com/wiki/Termux-dialog) if Termux:API app installed.

> Could you add exit options

It able to add such feature.But I don't feel it is very important because Ctrl+C can be used to exit.

> and color if I have installed but late in update

Already planned in #9, but As shown in https://github.com/gnuhead-chieb/revanced-automatic-builder/issues/10#issuecomment-1287715662 it isn't possible to fetch current version of apps from Termux without Root/ADB due to Android limitation
